name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: make deploy
      run: make deploy

    - name: make init
      run: make init

    - name: Load .zprofile
      run: |
        zsh ~/.zprofile 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .zshrc
      run: |
        zsh ~/.zshrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi
